### ISSUE TITLE
The highlight is not working correctly

### ISSUE THREAD

**Issue by Tekbr** [SirTori/indenticator#10]
-- Sorry for the English, I used Google Translator --

Compare VSCode-Insiders 1.13.0 with VSCode Stable 1.12.2.

Here is a comparison image.

![highlights](https://cloud.githubusercontent.com/assets/19866231/26126484/213c93c6-3a5c-11e7-95f5-82045dc4b858.png)

No configuration on its extension other than the default. I simply installed it.

I have activated: `"editor.renderIndentGuides": true`

**Comment by SirTori** [comment]
Hi,
thanks for bringing this to my attention.
I could confirm it and will look into it within this week

**Comment by SirTori** [comment]
I just updated the insider build and the problem has been solved. Seems it wasn't an intentional change by Microsoft.
If it does return until the next release I will reopen this but for now i guess the issue is resolved.

If you still have the problem after updating your insider build please let me know.

**Comment by Tekbr** [comment]
@SirTori In fact, the problem no longer occurs in the latest version of VSCode-insiders. Anyway thanks for the attention. And congratulations on the extension.
