### ISSUE TITLE
Install, remove bug

### ISSUE THREAD

**Issue by sshmyg** [SirTori/indenticator#19]
Hi, I've install `indenticator` and got such ugly highlight http://prntscr.com/j6udo8
But very strange, when I remove this plugin, this ugly highlight is still here.

__vs code 1.22.2, 10.13.4 osx high siera__

Any advice how to turn off this highlight?
Thnk's

**Comment by SirTori** [comment]
Hi,
I am sorry you've got problems with this extension. I don't have a mac to test your exact configuration, but running 1.22.2 on Windows I can't reproduce this behavior.
Have you done any configuration for the extension? What other Extensions do you have installed, maybe a combination of multiple extensions results in this behavior?

Also after successfully removing the plugin and restarting the editor the extension shouldn't be able to still influence anything since it is no longer loaded into your editor.  The extension itself does not install or uninstall anything - that is completely handled by the editor. The extension just tells the editor what it wants to be done once it has been installed and activated - as long as the editor doesn't load/activate it, it can't influence anything.

Since I can't reproduce this and haven't heard of this problem from anyone before I too can only guess for now.
For starters, if not already done so, I would suggest trying to reinstall and uninstall the extension again, since my first guess is that the editor had a problem with either of those steps.

**Comment by sshmyg** [comment]
@SirTori I was reinstalling a couple of times and no effect. Also try to install extn. with same behaviour.
Didn't change any configuration, just install, saw broken highlight and remove it.
 
Maybe you have an idea how to debug this issue? I can help to do it with osx.

**Comment by SirTori** [comment]
Today at work I tested this on a Mac with high siera 10.13.4 and I still was not able to reproduce the problem.

I am sorry to say I don't really know where to begin with debugging this.
The horizontal lines at the start and end of the vertical line seem very strange to me since the vertical line is done by rendering a border on a range of 0 characters (start and end of range is the same) - you can see this by increasing the zoom level (see image)
![indent_render](https://user-images.githubusercontent.com/7432341/38983159-fba60378-43c3-11e8-9123-7730350a4799.png)
So a horizontal line being wider than the borders rendered for the vertical one seems very srtange to me. Espacially since they don't even start aligned with the vertical one. All this indicates that it is not rendered because of the border definitions of the vertical line since the border definitions in this extension are always on all four sides of the specified ranges. That would leave them being drawn by another extension or simply a render bug within the editor.

Regarding the install/uninstall Problem sadly I can't help much either. As explained before the install/uninstall is completely handled by visual studio code. The code of this extensions is only running when loaded for an opened editor window.

Another suggestion would be uninstalling/reinstalling visual sutdio code itself, if not done already. Not being able to uninstall an extension completely sounds to me like there might be something wrong with your install. For saving settings and extensions you could try out this extensions: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync .

**Comment by sshmyg** [comment]
@SirTori Thanks, will try to reinstall.

**Comment by sshmyg** [comment]
Found out what's wrong. Sorry for the bug, it's not bound with your extension at all.
Problem with `Bracket Pair Colorizer` but I have no idea how, when and who installed it.
Sorry.
